// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4jQcehJ0ekAj1z3Or8qZcRczuji0BcgE',
    appId: '1:510959666422:web:b4a1c18ab247c6fe6798d7',
    messagingSenderId: '510959666422',
    projectId: 'speakfree-28159',
    authDomain: 'speakfree-28159.firebaseapp.com',
    storageBucket: 'speakfree-28159.appspot.com',
    measurementId: 'G-MTF7P6XSW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxtUZw3acxp1oK0lZ-DTN42ER4vAn7jTM',
    appId: '1:510959666422:android:3d8ef45330fafca36798d7',
    messagingSenderId: '510959666422',
    projectId: 'speakfree-28159',
    storageBucket: 'speakfree-28159.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZVso5ke2M_7y6yfaruPJNoa_fQMmUc0M',
    appId: '1:510959666422:ios:e743c9e77c01453a6798d7',
    messagingSenderId: '510959666422',
    projectId: 'speakfree-28159',
    storageBucket: 'speakfree-28159.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZVso5ke2M_7y6yfaruPJNoa_fQMmUc0M',
    appId: '1:510959666422:ios:e743c9e77c01453a6798d7',
    messagingSenderId: '510959666422',
    projectId: 'speakfree-28159',
    storageBucket: 'speakfree-28159.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4jQcehJ0ekAj1z3Or8qZcRczuji0BcgE',
    appId: '1:510959666422:web:7f5371cbe65bada26798d7',
    messagingSenderId: '510959666422',
    projectId: 'speakfree-28159',
    authDomain: 'speakfree-28159.firebaseapp.com',
    storageBucket: 'speakfree-28159.appspot.com',
    measurementId: 'G-PLVMX5NPFP',
  );
}
